### PR TITLE
add \a \b \v for correct escaping

### PR DESCRIPTION
**Pull request by fe-dagostino**
Please review or regenerate both scanner.c and scanner.h with your lex since I saw some difference with the version I have that is flex 2.6.4 .

### CODE REVIEW

**Review by hyperrealm — COMMENTED** [review]
This looks fine but can you please update the documentation accordingly. (libconfig.texi file)

I am also using flex 2.6.4 but it appears your flex did not generate these files correctly. Are you doing this on Windows?

**Comment by fe-dagostino** [comment]
Updated libconfig.texi with those little changes.

Linux user here !  are you using to pass some options? I had to modify it manually in order to get it working, was fast but unusual.

**Comment by hyperrealm** [comment]
The makefile regenerates the scanner.c and scanner.h automatically, and the options to flex are inside scanner.l.

Not sure why this isn't working for you, but how about you revert those generated files, then we'll merge your change and I'll regenerate them.

**Comment by fe-dagostino** [comment]
Hi Mark, to achieve that I guess the best way is to overwrite new scanner.c and scanner.h with old version using a new commit.
Then try to generate both with the makefile.
I think you have write access to my fork, otherwise I will do it tomorrow since now I'm from mobile.

**Comment by fe-dagostino** [comment]
Hi Mark, done! you can now merge and regenerate in your environment.

**Pull request merged**
